name: CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sail
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: docker version

      - name: Start Laravel Sail
        working-directory: ./laravel-app
        run: |
          cp .env.example .env
          ./vendor/bin/sail up -d
          ./vendor/bin/sail composer install
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force

      - name: Run Laravel Tests
        working-directory: ./laravel-app
        run: ./vendor/bin/sail test

  next-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./next-frontend
        run: npm ci

      - name: Run Next.js Tests
        working-directory: ./next-frontend
        run: npm run test
