name: CI Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: docker version

      - name: Start Laravel Sail
        working-directory: ./laravel-backend
        run: |
          cp .env.example .env
          docker run --rm -v $(pwd):/app -w /app composer install
          ./vendor/bin/sail up -d

      - name: Wait for MySQL to be ready
        working-directory: ./laravel-backend
        run: |
          for i in {1..10}; do
            ./vendor/bin/sail mysql -h mysql -u sail -ppassword -e "SELECT 1" && echo "MySQL is up" && break
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run Laravel setup
        working-directory: ./laravel-backend
        run: |
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force

      - name: Run Laravel Tests
        working-directory: ./laravel-backend
        run: ./vendor/bin/sail test

  next-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./next-frontend
        run: npm ci

      - name: Run Next.js Tests
        working-directory: ./next-frontend
        run: npx jest

  cypress-e2e:
    runs-on: ubuntu-latest
    needs: [laravel-tests, next-tests]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: docker version

      - name: Start Laravel Sail
        working-directory: ./laravel-backend
        run: |
          cp .env.example .env
          docker run --rm -v $(pwd):/app -w /app composer install
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./next-frontend
        run: npm ci

      - name: Start Next.js dev server
        working-directory: ./next-frontend
        run: npm run dev &
        
      - name: Wait for services to be ready
        run: |
          npx wait-on http://localhost:3000
          curl -s --fail http://localhost:3000 || (echo "Next.js not responding" && exit 1)
          sleep 5

      - name: Run Cypress tests
        working-directory: ./next-frontend
        run: npx cypress run

      - name: Upload Cypress videos (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: ./next-frontend/cypress/videos

      - name: Upload Cypress screenshots (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: ./next-frontend/cypress/screenshots
