name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  id-token: write    

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout entire repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # PR の差分ファイルまで取得する

      - name: Run Claude Code Review
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.MY_SECRET_KEY }}
          direct_prompt: |
            Review the PR changes. Focus on code quality, potential bugs, performance, and suggest improvements.
